# This exists solely to remove the pesky "...only implicit localhost is available" error
all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
