- name: Remove files
  vars:
    release_number: "{{ (install_type == 'ocp') | ternary(ocp_release, okd_release) }}"
    bin_name: "{{ (install_type == 'ocp') | ternary('openshift-install', 'okd-install') }}"
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - "{{ lookup('env', 'HOME') }}/bin/{{ bin_name }}"
  - "{{ lookup('env', 'HOME') }}/bin/{{ bin_name }}-{{ release_number }}"
  - /tmp/openshift-install
  - "/tmp/oc-{{ oc_release }}.tar.gz"
  - /tmp/oc
  - "{{ lookup('env', 'HOME') }}/bin/oc-{{ oc_release }}"
  - "{{ lookup('env', 'HOME') }}/bin/oc"
