# Install OCP or OKD. Valid values are ocp or okd
install_type: okd

# Installation executable
install_executable: "{{ (install_type == 'ocp') | ternary('openshift-install', 'okd-install') }}"

# URL to download OC cli
oc_url: "https://mirror.openshift.com/pub/openshift-v4/clients/oc/{{ oc_release }}/linux/oc.tar.gz"

# URL to extract OKD installation binary
okd_url: "registry.svc.ci.openshift.org/origin/release:{{ okd_release }}"

# URL to download OpenShift installation binary
ocp_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_release }}/openshift-install-linux.tar.gz"
