#!/usr/bin/env ansible-playbook
---
- name: Teardown OpenShift / OKD
  hosts: "{{ libvirt_host }}"
  gather_facts: false
  vars_files:
  - "{{ playbook_dir }}/../defaults/main.yml"
  tasks:
  - name: Remove entries in /etc/hosts
    become: true
    blockinfile:
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{ cluster_name }} -->"
      path: /etc/hosts

  - name: Destroy virtual machines
    vars:
      # Utility host is always deployed on Fedora CoreOS
      coreos_type: "{{ (install_type == 'ocp' and
                        vm.type != 'utility')
                    | ternary('redhat', 'fedora') }}"
      ignition_path: "{{ ignition_directory }}/{{ vm.type }}.ign"
      vm_name: "{{ vm.name }}"
      vm_mac: "{{ vm.mac }}"
      vm_cpus: "{{ vm.cpus }}"
      vm_memory: "{{ vm.memory }}"
      vm_disk_size: "{{ vm.disk_size }}"
      vm_network_name: "{{ cluster_name }}.{{ network.domain_suffix }}"
      vm_network_bridge: "{{ network.bridge_name }}"
      teardown: true
    include_role:
      name: libvirt_coreos_vm
    loop: "{{ cluster_vms }}"
    loop_control:
      loop_var: vm

  - name: Delete ignition files
    vars:
      teardown: true
    include_role:
      name: generate_ignition_files

  - name: Destroy libvirt network
    virt_net:
      state: absent
      name: "{{ cluster_name }}.{{ network.domain_suffix }}"
